### ISSUE TITLE
Endless reloading of todo app due to possible improper *time handling

### ISSUE THREAD

**Issue by robby-robby** [tractordev/wanix#104]
when running `make dev` navigating to http://localhost:7777 then `open todo`, the todo app will start, but then continually refresh until you kill the backend. 

-  "it could have to do with file access times changing"
-  "@Parzival-3141 made sure everything has proper ctime, mtime, and i think atime and maybe we're not filtering properly and every access looks like a change"

**Comment by progrium** [comment]
I believe this has been resolved!
