### ISSUE TITLE
shell rebuild

### ISSUE THREAD

**Issue by taramk** [tractordev/wanix#123]
shell is not rebuilt if you edit its source and reload the page.

we think its because the kernel just overwrites the shell binary in /sys/bin every time. it should check its mtime.

**Comment by Parzival-3141** [comment]
This is tricky since the shell binary in `kernel/bin/` loses it's `mtime` data when embedded in the kernel binary, so there's nothing to compare against. We could instead only embed if the user manually built the shell outside wanix.

**Comment by progrium** [comment]
i *think* the only thing getting in the way of it working right is just that we always set sys/bin/shell.wasm with the embedded version at sys/cmd/kernel/bin/shell ... and this should only ever happen if sys/bin/shell.wasm doesn't exist. so maybe its as simple as checking if it exists before the move/rename

**Comment by Parzival-3141** [comment]
That definitely works. I assumed it was to support dev workflow, building the shell out of band. In that case, with these changes, you could delete the shell binary before reloading.

**Comment by Parzival-3141** [comment]
Ideally we'd avoid embedding the shell at all to save on binary size. Could copy from `/sys/dev/local/bin` instead, which has `mtime` data.

**Comment by progrium** [comment]
right, it turns out to be a hard problem. we want first boot to be fast and not build, so it needs to embed it.

**Comment by Parzival-3141** [comment]
Ah right. I'll do it the first way then.

**Comment by Parzival-3141** [comment]
@progrium is it important that we copy in all files from `KernelSource`? It'd shorten bootup time if checked for existing binaries before copying. We could avoid embedding the source as well if only the binaries are necessary.
