### ISSUE TITLE
customization screen for chat mocks

### ISSUE THREAD

**Issue by taramk** [tractordev/wanix#129]
![Image](https://github.com/tractordev/wanix/assets/1813419/96366254-e07b-4986-aab8-077cbc88f736)

show the end result of customizing. a game over a chat window. don't need the controls (mic, hang up, etc.)

![Image](https://github.com/tractordev/wanix/assets/1813419/9d3c0dff-2daf-40e7-91cc-83739c94b57f)

**Comment by progrium** [comment]
to close these out can i get large png exports of the screens?

**Comment by taramk** [comment]
[Treecord images.zip](https://github.com/tractordev/wanix/files/14527749/Treecord.images.zip)
Attached!
