### ISSUE TITLE
Reproduce Go version bug

### ISSUE THREAD

**Issue by taramk** [tractordev/wanix#134]
compile: version "go1.21.1" does not match go tool version "go1.21.0"
 1.22.1 works

**Comment by Parzival-3141** [comment]
I'm unable to reproduce on my machine (Windows go1.21.1). I'm unsure why this bug happens. The [documentation](https://go.dev/doc/toolchain) doesn't shed much light, and the only other occurrence has been #72. 

We need more data, so I think we should put this in the "soon" pile until someone else hits it.

**Comment by progrium** [comment]
Yep, we'll just close actually for now until somebody reports it again.
