### ISSUE TITLE
Look into winget for CLI wanix

### ISSUE THREAD

**Issue by taramk** [tractordev/wanix#140]
Find out where the docs are to set that up and create an outline of what's necessary to set it up

**Comment by progrium** [comment]
Presumably if installer type is exe it can just be an executable?

**Comment by Parzival-3141** [comment]
It seems so. The only requirement seems to be options for silent installs. E.g. bypassing the GUI wizard

**Comment by progrium** [comment]
But is the exe expected to be an installer or can it be the executable that's installed? How do we get a `wanix` binary put somewhere it can be called (PATH or whatever)? Can you see what some other simple CLI utilities are doing?
