### ISSUE TITLE
service worker fails on firefox

### ISSUE THREAD

**Issue by progrium** [tractordev/wanix#20]
<img width="723" alt="Screen Shot 2023-11-17 at 5 38 06 PM" src="https://github.com/tractordev/wanix/assets/647/7fbe2b46-b849-44ec-87f9-0765d8729d85">

It's probably something stupid.

**Comment by Parzival-3141** [comment]
Seems to be an issue here:
https://github.com/tractordev/wanix/blob/e2add27dc5f89da98e141eeb29f06c884fae77d9/dev/bootloader.js#L21

**Comment by progrium** [comment]
import.meta wasn't available in the service worker context on firefox
