### ISSUE TITLE
rework build system

### ISSUE THREAD

**Issue by progrium** [tractordev/wanix#5]
We want the `build` command to include everything it needs to build. We can do this by making the binary a polyglot file, where it is literally an executable followed by a zip file as one file. The zip file contains `compile`, `link`, and all the `.a` files of the standard library (plus whatever else we need to build wanix components). The `build` command can write these files out to `/tmp`, or with a zipfs it could temporarily mount itself (being a zip) file to a location. Then it can run as normal and then clean up.

**Comment by Parzival-3141** [comment]
Running into a linker issue, not entirely sure yet how to fix.
![image](https://github.com/tractordev/wanix/assets/29632054/cb26a746-2aa9-4e4c-aa7a-877e1ebe1bb6)

It seems the linker errors come from whether [`Library.Main`](https://cs.opensource.google/go/go/+/master:src/cmd/link/internal/sym/library.go;l=18;drc=01dfae914bb4658d096c3ab8f5210bcf3f665171;bpv=1;bpt=1) is set to true. It's only [set](https://cs.opensource.google/go/go/+/master:src/cmd/link/internal/ld/go.go;l=55;drc=01dfae914bb4658d096c3ab8f5210bcf3f665171;bpv=1;bpt=1) and [read](https://cs.opensource.google/go/go/+/master:src/cmd/link/internal/ld/lib.go;l=1076;drc=01dfae914bb4658d096c3ab8f5210bcf3f665171;bpv=1;bpt=1) here. Here's the [blame](https://cs.opensource.google/go/go/+/699b0d4e52f32234e21358d3a0b9485b01c13236) for the check as well.

**Comment by progrium** [comment]
I think it's worth looking into the main.a the compiler outputs. Maybe compare the binary output of the old working prototype compile and see if there's anything significantly different. If there's not a lot of ways for the linker to get to `library.Main = false`, it makes me think something is wrong/different with `main.a`

**Comment by taramk** [comment]
the problem seems to be in the compiled-out wasm (update from julian)
