### ISSUE TITLE
fs: temp directory semantics

### ISSUE THREAD

**Issue by Parzival-3141** [tractordev/wanix#55]
One thing I find particularly annoying about Windows is that unlike Linux there are no guarantees for when temporary directories are deleted. This leads to drive bloat and shoddy programs which rely on temp-dirs for long term storage, potentially causing issues if you just wipe the whole thing. Blech.

I propose clearing the system temporary directory (i.e. `/tmp` or `/sys/tmp`, etc.) at shutdown. This gives programs an easy caching solution while forcing them elsewhere for long term storage, as the user could reset the system at any time. 

This could be implemented as a `memfs` mounted to `/tmp`, being cleared alongside Wanix when the browser ends the process.

The build tool was written assuming this behavior, although it can be changed if this proposal is rejected.

**Comment by progrium** [comment]
Great idea, great implementation!
