### ISSUE TITLE
external/micro

### ISSUE THREAD

**Issue by progrium** [tractordev/wanix#6]
`micro` is missing from the new setup. In part, we needed a new way to include it that isn't dropping in binary blobs into the repo. Instead of having my fork exists, which is very specific to wanix, I think we should make a `external/micro` dir that pulls in a particular version of the micro repo (gitignored) and then applies the patches I made. The patches can be versioned here in the `external/micro` directory. A `Makefile` can set all this up and produce a binary that goes in the staging `bin` directory.

**Comment by Parzival-3141** [comment]
Currently blocked by #36

**Comment by Parzival-3141** [comment]
I did some printf debugging in micro's `tcell` dependency, and it seems like it's hanging in `tscreen.mainLoop()`
![image](https://github.com/tractordev/wanix/assets/29632054/e81e3e06-fb98-4d00-8109-1c067225f41c)
https://github.com/zyedidia/tcell/blob/969958742a553232cbae8fcc291907a98e57b860/tscreen.go#L1598
