### ISSUE TITLE
httpfs: hanging on non-existent files

### ISSUE THREAD

**Issue by robby-robby** [tractordev/wanix#75]
The 'invalid directory' error is not thrown for directories which do not exist, 3 levels deep plus. Observing the following:

```sh
/ ▶ cd /foobar
invalid directory

/ ▶ cd /sys/foobar      
invalid directory

/ ▶ cd  /sys/dev/foobar 
[ hangs here, no error ]
```

**Comment by progrium** [comment]
Another great find. This isn't related to depth as much the special `httpfs` filesystem mounted at `/sys/dev` by the dev server. Apparently it doesn't handle non-existent files well.
