### ISSUE TITLE
user identity

### ISSUE THREAD

**Issue by progrium** [tractordev/wanix#76]
The kernel needs to have some kind of vaguely PAM-like system to support multiple ways to optionally authenticate as a particular user and then expose that user identity to the environment. I want to support an Auth0 based auth flow, but a pure passkey flow would also be nice to start. 

This also gets into configuring the kernel/bootloader as this would be domain/deployment specific.

**Comment by taramk** [comment]
consists of a variable and a syscall

**Comment by taramk** [comment]
@progrium jeff to update issue
