### ISSUE TITLE
Invalid mv command input causes a panic in `syscall/js`

### ISSUE THREAD

**Issue by taramk** [tractordev/wanix#79]
![image](https://github.com/tractordev/wanix/assets/1813419/ec348bab-69fe-4359-87d2-76715da665e8)

The mv command I used here was invalid (in several ways) but the terminal just hangs and does not show the user an error.

**Comment by Parzival-3141** [comment]
Looking at the console output it seems to be panicking in `syscall/js`.
![image](https://github.com/tractordev/wanix/assets/29632054/f46be274-5bd4-4215-872b-11ce5881f7da)
I believe it's erroring [in `syscall/js`](https://cs.opensource.google/go/go/+/refs/tags/go1.21.6:src/syscall/js/js.go;l=84-87), where it's incorrectly trying to access a field of a string type `jsValue`. The error is bubbling up from the call to `getFileKey`. https://github.com/tractordev/wanix/blob/85b913801650a05ec3d764a91c25f40890ee497f/internal/indexedfs/indexedfs.go#L248-L251
