### ISSUE TITLE
Verify Safari (and Arc) compatibility

### ISSUE THREAD

**Issue by taramk** [tractordev/wanix#90]

**Comment by taramk** [comment]
tested on safari 16 & 17 with no issues.
tested in arc on another OS with no issues. 
there's just something wrong with my main OS, i guess 😢

**Comment by progrium** [comment]
maybe you have weird extensions installed?

**Comment by taramk** [comment]
it seems like too much of a coincidence that i had issues testing the darwinkit apps too, and those didn't involve the browser.
